### ISSUE TITLE
Update Discord Invitation Links

### ISSUE THREAD

**Issue by schmelto** [EddieHubCommunity/support#1401]
Chang to http://discord.eddiehub.org 

- [x] readme.md (#1402)
- [x] /.github/ISSUE_TEMPLATE/bug.md (#1403)
- [x] /.github/ISSUE_TEMPLATE/gh-profile-review.md (#1402)
- [x] /.github/ISSUE_TEMPLATE/opensource-review.md (#1402)
- [x] /.github/ISSUE_TEMPLATE/portfolio-review.md (already done see [here](https://github.com/EddieHubCommunity/support/issues/1401#issuecomment-827207899)) 
- [x] /.githubISSUE_TEMPLATE/resume-review.md (#1402)

see [here](https://github.com/EddieHubCommunity/EddieHubCommunity.github.io/issues/163)

**Comment by Evavic44** [comment]
Can I fix more than one?

**Comment by schmelto** [comment]
> Can I fix more than one?

sure :)

**Comment by Evavic44** [comment]
Hello @schmelto, I think in the `/.github/ISSUE_TEMPLATE/portfolio-review.md` file, EddieHub Discord link has already been updated. See attached.
![Annotation 2021-04-27 003248](https://user-images.githubusercontent.com/62628408/116163863-7f1e8300-a6f0-11eb-881e-7e4caafae309.png)

**Comment by schmelto** [comment]
> Hello @schmelto, I think in the `/.github/ISSUE_TEMPLATE/portfolio-review.md` file, EddieHub Discord link has already been updated.

Oh yes thanks for discovering 🚀  I've updated the description above 👍🏼

**Comment by mertbozkir** [comment]
is this issue closed? I mean is it finished?

I would try to help @schmelto

**Comment by schmelto** [comment]
> is this issue closed? I mean is it finished?
> 
> I would try to help @schmelto

All task for this issue are done. Issue is still open due the PRs are not merged yet.

If you want a similar issue see here https://github.com/EddieHubCommunity/gh-action-open-source-labels/issues/12

**Comment by mertbozkir** [comment]
Thank you folk 🪐
