### ISSUE TITLE
[REVIEW] numanjvd82/todo-list

### ISSUE THREAD

**Issue by numanjvd82** [EddieHubCommunity/support#1671]
**Todo List**
https://github.com/numanjvd82/todo-list

Wanted to made it with context API but I didn't know at the time. :)

You can also join the discord community [here](http://discord.eddiehub.org)

Feel free to check out other cool repositories of EddieHub Community [here](https://github.com/EddieHubCommunity)

**Comment by Ayush7614** [comment]
> **Todo List**
> https://github.com/numanjvd82/todo-list
> 
> Wanted to made it with context API but I didn't know at the time. :)
> 
> You can also join the discord community [here](http://discord.eddiehub.org)
> 
> Feel free to check out other cool repositories of EddieHub Community [here](https://github.com/EddieHubCommunity)

Hey @numanjvd82 it looks good you work was very good but i have give you one suggestion that plss improves the readme it looks more cool if you readme was good then other peoples was also known what is this full project you can take this example for sample [sample](https://github.com/Ayush7614/Score-App/blob/main/README.md) this is my project look at the readme [sample 2](https://github.com/Ayush7614/Daily-Coding-DS-ALGO-Practice/blob/main/README.md)

**Comment by numanjvd82** [comment]
Yeah sure i would update as soon as  i can shave some time for github.

**Comment by shubhendumadhukar** [comment]
When I create/delete a todo, entire page shifts down when the toast is displayed. It's not a big issue but it could be made better in terms of user experience, if the toast didn't impact the other components. You could probably use the `z-index` property with `position: fixed` in your CSS to make the toast seems detached from rest of the page.

![test](https://user-images.githubusercontent.com/10685907/120064683-204f7f00-c08b-11eb-9c88-a1bb3b9e46c4.gif)

**Comment by schmelto** [comment]
Maybe also add some prerequisites Fr running in local like node installed etc.

**Comment by krishdevdb** [comment]
## Requested Changes 😉
- [ ] Live Preview Can Be Also The Repository Website URL
- [ ] Add more to the readme: refer #1553
- [ ]  Repository Description
- [ ] Code of conduct and contributing
- [ ] License
- [ ] Issue/PR Templates
- [ ] @shubhendumadhukar's suggestion: https://github.com/EddieHubCommunity/support/issues/1671#issuecomment-850800884
- [ ] Logo as simple as #1561
- [ ] CI Build GitHub Actions
- [ ] Take a look at #1726 
- [ ] Commit style: either https://conventionalcommits.org or https://gitmoji.dev

## Feedback
- [x] Webpage Looks Cool 🤩 
- [x] Responsiveness 😍 
- [x] Project Tech Stack ❤️   

**Copy This Checklist Paste It Into An Comment Then Keep It Updated With Your Workflow. I will update mine once I see your checklist is updated 😃**

**Comment by numanjvd82** [comment]
Actually i made a todo-list-v2 where i implemented context api and the toast also has a position fixed wit

> ## Requested Changes 😉
> * [ ]  Live Preview Can Be Also The Repository Website URL
> * [ ]  Add more to the readme: refer #1553
> * [ ]   Repository Description
> * [ ]  Code of conduct and contributing
> * [ ]  License
> * [ ]  Issue/PR Templates
> * [ ]  @shubhendumadhukar's suggestion: [#1671 (comment)](https://github.com/EddieHubCommunity/support/issues/1671#issuecomment-850800884)
> * [ ]  Logo as simple as #1561
> * [ ]  CI Build GitHub Actions
> * [ ]  Take a look at #1726
> * [ ]  Commit style: either https://conventionalcommits.org or https://gitmoji.dev
> 
> ## Feedback
> * [x]  Webpage Looks Cool 🤩
> * [x]  Responsiveness 😍
> * [x]  Project Tech Stack ❤️
> 
> **Copy This Checklist Paste It Into An Comment Then Keep It Updated With Your Workflow. I will update mine once I see your checklist is updated 😃**

Thank you for your feedback. I actually made a todo-list-v2 where i implemented context api and made my code cleaner and scalable for future additions.
I will also try to update my project repo using your checklist.
Thank you again for your time.

**Comment by numanjvd82** [comment]
> When I create/delete a todo, entire page shifts down when the toast is displayed. It's not a big issue but it could be made better in terms of user experience, if the toast didn't impact the other components. You could probably use the `z-index` property with `position: fixed` in your CSS to make the toast seems detached from rest of the page.
> 
> ![test](https://user-images.githubusercontent.com/10685907/120064683-204f7f00-c08b-11eb-9c88-a1bb3b9e46c4.gif)

check out my todo-list-v2 i fixed that issue with the toast and also a search bar for searching todos.

**Comment by eddiejaoude** [comment]
Thank you for sharing, we will review on a live stream soon 👍 It looks like you are getting great community feedback already 💥
