### ISSUE TITLE
[REVIEW] Mahmoud Farargy

### ISSUE THREAD

**Issue by Mahmoud-farargy** [EddieHubCommunity/support#2545]
### GitHub Profile Link

https://github.com/Mahmoud-farargy/instagram-clone

**Comment by krshkun** [comment]
Hi there 👋 I have a few suggestions and improvements for your profile

## 📝 Suggestions

- [ ] Add a Code of Conduct: https://github.com/Mahmoud-farargy/instagram-clone/issues/49
- [ ] Add contributing guidelines: https://github.com/Mahmoud-farargy/instagram-clone/issues/50
- [ ] Issue templates: https://github.com/Mahmoud-farargy/instagram-clone/issues/51
- [ ] PR Template: https://github.com/Mahmoud-farargy/instagram-clone/issues/52
- [ ] Use Issues, I see you make a lot of PRs, maybe link them with issues
- [ ] The preview screenshots are good, but they are too big, maybe try reducing their size
- [ ] The readme headings can have emojis 🎨 
- [ ] Readme directly starts with description which is already on the right menu, maybe have the project name as a heading instead of that
- [ ] You can have the screenshots folder inside a .github folder so that it is hidden, and only it has capitalized name, others don't so maybe keep them consistent
- [ ] I see you have cypress and tests - you can have CI using github actions: https://github.com/Mahmoud-farargy/instagram-clone/issues/53
- [ ] You have a netlify.toml file, you can include a deploy on netlify button
- [ ] You can also add a gitpod button for people willing to open and see the code: https://github.com/Mahmoud-farargy/instagram-clone/issues/54
- [ ] There is no particular code style, you can setup eslint or prettier it will help you be consistent: https://github.com/Mahmoud-farargy/instagram-clone/issues/56

## 🤔 Questions

- Maybe you can not call this an instagram clone, this will help you showcase it as a personal project- social media site which shows a lot about your learning and also signifies that you didn't copy instagram but tried to create something that is yours
- Do you know that you can rename the domain provided my netlify to something more human friendly and readable?

## 🚀 Appreciation

- [x] The design and implementations is very cool
- [x] You use PRs and branches
- [x] You have screenshots and deployed links in your readme 😍

**Comment by eddiejaoude** [comment]
Reviewed on live stream...

Looks good, some thoughts:
- releases and packages are not used, suggest hiding these
- highly recommend adding a Code of Conduct
- missing contributors file
- maybe add issue templates
- use GitHub Action to build project and run cypress tests
