### ISSUE TITLE
Renew the name of the community in the Issue Templates

### ISSUE THREAD

**Issue by SashoStoichkov** [EddieHubCommunity/support#881]
## The Issue
In some of the Issue templates in this repo still have the old name `Eddie Jaoude Community`

I suggest we should replace them with the new one `EddieHub`

## The Solution

For example: wherever in `.github/ISSUE_TEMPLATE/*.md` there is this sentence:
- `Feel free to check out other cool repositories of Eddie Jaoude Community [here](https://github.com/EddieJaoudeCommunity)`

It should be replaced with that:
- `Feel free to check out other cool repositories of EddieHub [here](https://github.com/EddieHubCommunity)`

## TODO:
- [x] `bug.md`
- [x] `community-question.md`
- [x] `general-question.md`
- [x] `resume-review.md`
- [x] `review-my-open-source-link.md`
- [x] `technical-question.md`

#EddieHub

**Comment by SashoStoichkov** [comment]
And also fix the links because they redirect to the 404 page

**Comment by SashoStoichkov** [comment]
For example: wherever in `.github/ISSUE_TEMPLATE/*.md` there is this sentence:
- `Feel free to check out other cool repositories of Eddie Jaoude Community [here](https://github.com/EddieJaoudeCommunity)`

It should be that:
- `Feel free to check out other cool repositories of EddieHub [here](https://github.com/EddieHubCommunity)`

**Comment by chryzcodez** [comment]
I am having difficulty in finding where this issue is located. Please can anyone help with that by send the link. 

I would really appreciate that!

**Comment by SashoStoichkov** [comment]
@chryzcodez https://github.com/EddieHubCommunity/support/tree/main/.github/ISSUE_TEMPLATE here you go 👍🏻

**Comment by chryzcodez** [comment]
The name of the community is EddieHub community not EddieHub.


To complete this is issue totally I would need to clone this repo into my machine and make the change once. After than I would make the pull request once than picking it one after the other!

**Comment by Vyvy-vi** [comment]
Maybe we should keep 1PR per issue rather than multiple pull requests?

**Comment by SashoStoichkov** [comment]
@chryzcodez Please don't complete the issue totally and spread the 🟩

**Comment by chryzcodez** [comment]
@vivek80801 that's what I had in mind! I already started that now. Working👨‍💻 on it presently

**Comment by SashoStoichkov** [comment]
> The name of the community is EddieHub community not EddieHub.

I am not really sure about that I think the community is called `EddieHub` not ~~EddieHub Community~~

**Comment by chryzcodez** [comment]
> > The name of the community is EddieHub community not EddieHub.
> 
> I am not really sure about that. I think the community is called `EddieHub` not ~EddieHub Community~

Ok, if so. The pull request would be modified!

**Comment by Vyvy-vi** [comment]
EddieHub is the name of the community... We use EddieHubCommunity on github since the username was taken

**Comment by chryzcodez** [comment]
> EddieHub is the name of the community... We use EddieHubCommunity on github since the username was taken

Ok, I just got to understand this more better. Thanks @Vyvy-vi

**Comment by bagladivyang03** [comment]
@Vyvy-vi could u pls check my pr and merge it.

**Comment by SashoStoichkov** [comment]
@bagladivyang03 don't worry - it will get merged eventually

**Comment by nhcarrigan** [comment]
@bagladivyang03 while I understand the excitement that comes with creating a PR, please note that open-source maintainers are people too. Many have other obligations, outside of the project you may have contributed to. Reviewing, approving, and merging a PR takes time - please have patience 🙂

**Comment by SashoStoichkov** [comment]
Yeah I agree with @nhcarrigan 👍🏻 
That was exactly what I meant

**Comment by bagladivyang03** [comment]
> @bagladivyang03 while I understand the excitement that comes with creating a PR, please note that open-source maintainers are people too. Many have other obligations, outside of the project you may have contributed to. Reviewing, approving, and merging a PR takes time - please have patience 🙂

Yeah sure will understand this :)

**Comment by bagladivyang03** [comment]
> @bagladivyang03 don't worry - it will get merged eventually

Yeah Thanks!!

**Comment by Vyvy-vi** [comment]
> @Vyvy-vi could u pls check my pr and merge it.

😅  I would definitely check it out and drop a review.. but I'm not a maintainer and can't merge PRs @bagladivyang03 
Also, maybe wait a bit.. Maintainers aren't always around and are usually busy and PRs get merged eventually  :+1:
Opensource takes some time :)

**Comment by bagladivyang03** [comment]
> > @Vyvy-vi could u pls check my pr and merge it.
> 
> 😅  I would definitely check it out and drop a review.. but I'm not a maintainer and can't merge PRs @bagladivyang03 
> Also, maybe wait a bit.. Maintainers aren't always around and are usually busy and PRs get merged eventually  :+1:
> Opensource takes some time :)

Yeah👍👍

**Comment by eddiejaoude** [comment]
Great discussion everyone 👍 - thank you all 🤓 

I am slowly catching up with GitHub notifications, it looks like the community is on top of it all 💪 #EddieHub FTW

**Comment by bagladivyang03** [comment]
#914

**Comment by bagladivyang03** [comment]
#914

**Comment by NIKU-SINGH** [comment]
Hey, I see the issue is still open so i would like to make  my first contribution.  I understand that i  need to change the name to EddiehubCommunity . But any update on this and guidance would be helpful.

**Comment by chryzcodez** [comment]
I think we need to close this issue. I feel it's all done in here.
