### ISSUE TITLE
Move Finding-Open-Source-Projects.md to the tips folder

### ISSUE THREAD

**Issue by BOLT04** [EddieHubCommunity/support#958]
**Description**

Currently, we have the `Finding-Open-Source-Projects.md` file on the root. When this file was created, we didn't have the `tips` folder.
As we grow the number of tips and content is created, it should all be organized on the `tips` folder.

**Tasks**
- [x] Move `Finding-Open-Source-Projects.md` to the `tips` folder
- [x] Change name to lower case to be consistent with the already existing file on the folder
- [x] Fix any path to this file. For example in the `README`:
![imagem](https://user-images.githubusercontent.com/18630253/108611032-5917f200-73d2-11eb-8d59-30756a41c764.png)

What does everyone think?

**Comment by vinzvinci** [comment]
I **agree**, it would be **better**.

**Comment by chryzcodez** [comment]
> **Description**
> 
> Currently, we have the `Finding-Open-Source-Projects.md` file on the root. When this file was created, we didn't have the `tips` folder.
> As we grow the number of tips and content is created, it should all be organized on the `tips` folder.
> 
> **Tasks**
> 
> * [ ]  Move `Finding-Open-Source-Projects.md` to the `tips` folder
> * [ ]  Change name to lower case to be consistent with the already existing file on the folder
> * [ ]  Fix any path to this file. For example in the `README`:
>   ![imagem](https://user-images.githubusercontent.com/18630253/108611032-5917f200-73d2-11eb-8d59-30756a41c764.png)
> 
> What does everyone think?

Where can I get the Finding-Open-Source-Projects.md file. Please can you share me the link to the file so that work can start as son as possible1

**Comment by chryzcodez** [comment]
Ok I already solved it, check out the pull request referenced here!

**Comment by SashoStoichkov** [comment]
closes #970 
closes #969
